### PR TITLE
update to recent paf and irmin

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
so this leads to successful compilation of dns-primary-git, but what is still missing are positive functional tests -- and what should be unrelated to let the git implementation use ipv4/ipv6 (by using happy-eyeballs within mimic/paf).

**Comment by hb9cwp** [comment]
@hannesm Yes correct. For the functional tests, I intended to get `Unipi hvt` target working first, as a Web server might  presumably "simpler" than an authoritative DNS server. But maybe I should try with `dns-primary-git` in the mean-time.
Also, so far, I was only testing against a public Github repo, because I could not figure out yet how to make Irmin (cohttp, etc.) accept my self-signed certificate which my internal Gitea instance uses.

**Comment by hb9cwp** [comment]
@hannesm After `unipi`, your `updat` branch of `dns-primary-git` builds and runs for both `unix` and `hvt` targets on OpenBSD 7.0 amd64 in an IPv4/IPv6 dual-stack setup. So far, I have only tested pulling the zone file from Github using HTTPS, as well as DNS queries to the unikernels' IPv4/6 addresses of its `tap` interface.
Next, I will try to get them working against my local Gitea, and setup post-commit hooks to send signed NOTIFIES with `onotify` :-)

**Comment by hannesm** [comment]
this was merged manually into the main branch.

**Comment by hannesm** [comment]
@hb9cwp how I have it set up is indeed a self-hosted gitea instance (git.robur.io), and I use git over ssh for the dns-primary-git, i.e.:
- execute "awa_gen_key" outputs (a) a seed (b) a ssh public key
- add a user to gitea with access to the right repository, and the public key from above as authentication mechanism
- run ssh-keygen -lf <(ssh-keyscan -t rsa git.robur.io 2>/dev/null)
- start the unikernel with `--seed=(a)` (from awa_gen_key) and `--authenticator=SHA256:<FP>` (from ssh-keyscan) and `--remote=git@git.robur.io:<my-repo.git>`

I used to suffer from some issues in the git-http transport (that may be fixed by now), and lack of knowledge how to setup http user authentication (before I started using gitea).

**Comment by hb9cwp** [comment]
@hannesm Thank you for guidance, which confirms what I tried to gather from your [post](Deploying authoritative OCaml-DNS servers as MirageOS unikernels) earlier, and encourages me to have another go using SSH with both public Github and Gitea today.

> I used to suffer from some issues in the git-http transport (that may be fixed by now)
Yesterday, I spent a quite a few hours to setup self-hosted Gitea for HTTPS correctly, e.g. providing it with fresh self-signed cert that matches its FQDN instead of server IP address, etc. With the result that the unikernels with debug log level fails now with
`...
147d?\252\222\255)o\133\211z\019\229\128.\246<\197\199MY\220\163\020\247t]Rl\205\000\000"))
irmin: [DEBUG] (fail-alert-out (FATAL BAD_CERTIFICATE))
irmin: [DEBUG] (failure
                (Error (AuthenticationFailure "invalid certificate chain")))
^C`
while current Chrome browser does not complain (though it shows warning in red "Not secure", of course). 

More irritating is the default log output on the side of the Gitea server which kept me from trying to resolve the problem above (10.0.0.7 is the `unix` unikernel that connects to Gitea on another OpenBSD host in the same local subnet):
`2021/11/09 10:05:13 ...c/net/http/server.go:3139:logf() [I] http: TLS handshake error from 10.0.0.7:35616: local error: tls: bad record MAC
`
According to a few reports, the Go library tends to log such errors if there are problems with checksum offloading to NICs, in my case a Realtek `re(4)`, whereas the unikernel's host has an Intel `em(4)`. However, with OpenBSD there is apparently no (quick) way to disable checksum offloading other than rebuiling the NIC drivers from source (or add another non-`re(4)` NIC to the Gitea host). Let's see if the SSH route is easier than debugging HTTPS further...

**Comment by hannesm** [comment]
The log output of gitea is indeed irritating. On the OCaml side, [this ocaml-git code](https://github.com/mirage/ocaml-git/blob/3.6.0/src/git-paf/git_paf.ml#L235-L291) plays a role, noteworthy:

```OCaml
  module Nss = Ca_certs_nss.Make (Pclock) (* https://github.com/mirage/ca-certs-nss package *)
  [...]
  let authenticator = Rresult.R.failwith_error_msg (Nss.authenticator ())
  let default_tls_cfg = Tls.Config.client ~authenticator ()
  [...]
     dft tls default_tls_cfg
```

Basically this means that the default authenticator is chain of trust validation of the server certificate, using the nss trust anchors (also used by mozilla firefox, ca-certs-nss extracts them from nss into OCaml). This also means that your self-signed certificate won't be authenticated by git-paf. The bad record mac may need some investigation, my expectation was a bad certificate sent by the OCaml client to the go server.

And (/cc @dinosaure) git-paf should offer other authenticators via boot parameters, so that you can specify your own CA certificate, a key or certificate fingerprint, etc. -- similar to what git_mirage_ssh does with the `--authenticator` argument (by using Awa.Keys.authenticator_of_string). Maybe worth to report an issue to the mirage/ocaml-git repository so that this won't be forgotten.

**Pull request closed without merging**
